apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hecate
resources:
  - namespace.yaml
  - configmap.yaml
  - sealed-secrets.yaml
  - headless-service.yaml
  - daemonset.yaml
