apiVersion: v1
kind: Service
metadata:
  name: git-server
  namespace: hecate
  labels:
    app.kubernetes.io/name: git-server
    app.kubernetes.io/part-of: hecate-system
spec:
  type: ClusterIP
  ports:
    - name: git
      port: 9418
      targetPort: 9418
      protocol: TCP
  selector:
    app: git-server
