apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: hecate-daemon
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: hecate-gitops
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: Flux Image Automation
        email: flux@hecate.social
      messageTemplate: |
        chore(deploy): update hecate-daemon to {{range .Changed.Changes}}{{.NewValue}}{{end}}
    push:
      branch: main
  update:
    path: ./infrastructure/hecate
    strategy: Setters
