apiVersion: v1
kind: ConfigMap
metadata:
  name: traderd-config
  namespace: hecate
data:
  TRADERD_DATA_DIR: "/home/rl/.hecate/hecate-traderd"
  TRADERD_SOCKET_PATH: "/home/rl/.hecate/hecate-traderd/sockets/api.sock"
